### ISSUE TITLE
json: Update fast-json-patch

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar_patterns#37]
laxar_patterns is still using a patched version of `fast-json-patch` 0.3.8.
We should update to the latest version, as it contains the [patch](Starcounter-Jack/JSON-Patch#52) and has some nice new features (for example, appending to arrays with `{ op: 'add', path: '/-' }`) and probably a lot of bugfixes.

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0`).

**Comment by alex3683** [comment]
@jpommerening Have fun with your `-` :)
